# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/friede/Documents/DIVE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/friede/Documents/DIVE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/friede/Documents/DIVE/CMakeFiles /home/friede/Documents/DIVE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/friede/Documents/DIVE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DIVE

# Build rule for target.
DIVE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DIVE
.PHONY : DIVE

# fast build rule for target.
DIVE/fast:
	$(MAKE) -f CMakeFiles/DIVE.dir/build.make CMakeFiles/DIVE.dir/build
.PHONY : DIVE/fast

#=============================================================================
# Target rules for targets named DIVE_cut

# Build rule for target.
DIVE_cut: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DIVE_cut
.PHONY : DIVE_cut

# fast build rule for target.
DIVE_cut/fast:
	$(MAKE) -f CMakeFiles/DIVE_cut.dir/build.make CMakeFiles/DIVE_cut.dir/build
.PHONY : DIVE_cut/fast

DIVE.o: DIVE.cpp.o
.PHONY : DIVE.o

# target to build an object file
DIVE.cpp.o:
	$(MAKE) -f CMakeFiles/DIVE.dir/build.make CMakeFiles/DIVE.dir/DIVE.cpp.o
.PHONY : DIVE.cpp.o

DIVE.i: DIVE.cpp.i
.PHONY : DIVE.i

# target to preprocess a source file
DIVE.cpp.i:
	$(MAKE) -f CMakeFiles/DIVE.dir/build.make CMakeFiles/DIVE.dir/DIVE.cpp.i
.PHONY : DIVE.cpp.i

DIVE.s: DIVE.cpp.s
.PHONY : DIVE.s

# target to generate assembly for a file
DIVE.cpp.s:
	$(MAKE) -f CMakeFiles/DIVE.dir/build.make CMakeFiles/DIVE.dir/DIVE.cpp.s
.PHONY : DIVE.cpp.s

DIVE_cut.o: DIVE_cut.cpp.o
.PHONY : DIVE_cut.o

# target to build an object file
DIVE_cut.cpp.o:
	$(MAKE) -f CMakeFiles/DIVE_cut.dir/build.make CMakeFiles/DIVE_cut.dir/DIVE_cut.cpp.o
.PHONY : DIVE_cut.cpp.o

DIVE_cut.i: DIVE_cut.cpp.i
.PHONY : DIVE_cut.i

# target to preprocess a source file
DIVE_cut.cpp.i:
	$(MAKE) -f CMakeFiles/DIVE_cut.dir/build.make CMakeFiles/DIVE_cut.dir/DIVE_cut.cpp.i
.PHONY : DIVE_cut.cpp.i

DIVE_cut.s: DIVE_cut.cpp.s
.PHONY : DIVE_cut.s

# target to generate assembly for a file
DIVE_cut.cpp.s:
	$(MAKE) -f CMakeFiles/DIVE_cut.dir/build.make CMakeFiles/DIVE_cut.dir/DIVE_cut.cpp.s
.PHONY : DIVE_cut.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... DIVE"
	@echo "... DIVE_cut"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DIVE.o"
	@echo "... DIVE.i"
	@echo "... DIVE.s"
	@echo "... DIVE_cut.o"
	@echo "... DIVE_cut.i"
	@echo "... DIVE_cut.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

